"""
Django settings for SCOB project.
Generated by 'django-admin startproject' using Django 5.0.7.
"""
# Force IPv4 to avoid Supabase IPv6 connection issues
import socket
original_getaddrinfo = socket.getaddrinfo

def ipv4_only_getaddrinfo(*args, **kwargs):
    return [ai for ai in original_getaddrinfo(*args, **kwargs) if ai[0] == socket.AF_INET]

socket.getaddrinfo = ipv4_only_getaddrinfo

from pathlib import Path
import os
import cloudinary
import cloudinary.uploader
import cloudinary.api
import dj_database_url
from decouple import config
import dj_database_url


BASE_DIR = Path(__file__).resolve().parent.parent

# Cloudinary config
cloudinary.config(
    cloud_name="dlzn0moho",
    api_key="942887989436842",
    api_secret="8_Hu2A6oefhgbHWGdA0cEehYerc"
)

from decouple import config

db_url = config('DATABASE_URL', default=None)
if isinstance(db_url, bytes):
    db_url = db_url.decode("utf-8")

DATABASES = {
    'default': dj_database_url.parse(db_url, conn_max_age=600)
}

# Add SSL mode if using Postgres
if 'postgres' in DATABASES['default']['ENGINE']:
    DATABASES['default']['OPTIONS'] = {'sslmode': 'require'}
    
# SECURITY
SECRET_KEY = config('SECRET_KEY', default='django-insecure-1fw)(+*&**t4_r@=-a%9)hstji&^ueabvfx)4=csjoafvzhnwg')
DEBUG = config('DEBUG', default=False, cast=bool)
ALLOWED_HOSTS = [
    "heritagebank-production.up.railway.app",
]

CSRF_TRUSTED_ORIGINS = [
    "https://heritagebank-production.up.railway.app",
]
# Installed apps
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'bank_app',
    'cloudinary',
    'cloudinary_storage',
]

# Media and Cloudinary file storage
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dlzn0moho',
    'API_KEY': '942887989436842',
    'API_SECRET': '8_Hu2A6oefhgbHWGdA0cEehYerc',
}

MEDIA_URL = '/media/'
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Templates
ROOT_URLCONF = 'SCOB.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SCOB.wsgi.application'

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Use WhiteNoise to serve static files in production
if not DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default auto field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
